export {
	clampElementToCanvas,
	createCircleElementFromDrag,
	createElementId,
	createImageElementFromDrag,
	createPathElementFromPoints,
	createRectElement,
	createRectElementFromDrag,
	createTextElementFromDrag,
	defaultElementName,
	duplicateElement,
	getElementBounds,
	getPathRenderTransform,
	getShapeDragBox,
	getTextLayoutMetrics,
	getWrappedTextLineHeight,
	getWrappedTextLines,
	getWrappedTextMetrics,
	MIN_SHAPE_SIZE,
	nextElementName,
	normalizeElement,
	normalizeElements,
	resizeImageFrameWithinCanvas,
	setElementPosition,
	translateElement,
	translateElementWithinCanvas,
	type ResizeHandle
} from "@app/internal/element-actions";
